[app]
server1 ansible_host=10.0.0.5
server2 ansible_host=10.0.0.6
server3 ansible_host=10.0.0.7

[all:vars]
ansible_user=app
ansible_password=Alex310224993
ansible_python_interpreter=/usr/bin/python3
